# Generated by Django 4.2.16 on 2024-12-05 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0002_buyer_delete_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="size",
            field=models.IntegerField(default=2),
        ),
    ]
