# Generated by Django 4.2.16 on 2024-12-05 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0003_userinfo_size"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userinfo",
            name="phoneId",
        ),
        migrations.RemoveField(
            model_name="userinfo",
            name="size",
        ),
    ]
