# Generated by Django 4.2.16 on 2024-12-05 05:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0004_remove_userinfo_phoneid_remove_userinfo_size"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name="Buyer",
        ),
        migrations.AddField(
            model_name="userinfo",
            name="account",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="create_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="gender",
            field=models.SmallIntegerField(choices=[(1, "男"), (0, "女")], default=1),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="age",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="name",
            field=models.CharField(max_length=24, verbose_name="姓名"),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app01.department",
            ),
        ),
    ]
