# Generated by Django 4.2.16 on 2024-12-08 04:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0005_department_delete_buyer_userinfo_account_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrettyNum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mobile", models.CharField(max_length=11, verbose_name="号码")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="价格"
                    ),
                ),
                (
                    "level",
                    models.SmallIntegerField(
                        choices=[(0, "高级"), (1, "中级"), (3, "低级")],
                        default=1,
                        verbose_name="级别",
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(0, "未占用"), (1, "已占用")], default=1, verbose_name="状态"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="account",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="账户"
            ),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="age",
            field=models.IntegerField(verbose_name="年龄"),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="create_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="入职时间"
            ),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app01.department",
                verbose_name="部门",
            ),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="gender",
            field=models.SmallIntegerField(
                choices=[(1, "男"), (0, "女")], default=1, verbose_name="性别"
            ),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="password",
            field=models.CharField(max_length=64, verbose_name="密码"),
        ),
    ]
